name: Hello greeting
on:
  issues:
    types: [opened,edited,closed]
  pull_request:
    types: [labeled]
jobs:
  hello-greeting:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: hello greeting
        uses: ./ #private action
      
